export enum StatusCadastro {
  PRE_CADASTRO = 'PRE_CADASTRO',
  PAGAMENTO_PENDENTE = 'PAGAMENTO_PENDENTE',
  PAGAMENTO_CONFIRMADO = 'PAGAMENTO_CONFIRMADO',
  PLANO_ATRIBUIDO = 'PLANO_ATRIBUIDO',
  ATIVO = 'ATIVO',
  COMPLETO = 'COMPLETO',
  PENDENTE_VALIDACAO = 'PENDENTE_VALIDACAO',
}
