import { DataSource } from 'typeorm';
import {
  Usuario,
  GrupoUsuario,
  AlunoInfo,
  AdministradorInfo,
  PlanoMestre,
  Plano,
  AlunoPlanos,
  PlanoMestreDisciplina,
  SprintMestre,
  Sprint,
  MetaMestre,
  Meta,
  Disciplina,
  Assunto,
  SprintAtual,
  RankingSemanal,
} from '../entities';

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: +(process.env.DB_PORT || 5432),
  username: process.env.DB_USERNAME || 'postgres',
  password: process.env.DB_PASSWORD || '1127',
  database: process.env.DB_DATABASE || 'mentoring',
  entities: [
    Usuario,
    GrupoUsuario,
    AlunoInfo,
    AdministradorInfo,
    PlanoMestre,
    Plano,
    AlunoPlanos,
    PlanoMestreDisciplina,
    SprintMestre,
    Sprint,
    MetaMestre,
    Meta,
    Disciplina,
    Assunto,
    SprintAtual,
    RankingSemanal,
  ],
  migrations: ['src/database/migrations/*.ts'],
  synchronize: false,
  logging: false,
});
